version: 0.2

phases:
  pre_build: # commands to be run before build
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      - eval $(aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 101327921112.dkr.ecr.ap-northeast-1.amazonaws.com)
      - REPOSITORY_URI=101327921112.dkr.ecr.ap-northeast-1.amazonaws.com/canvas-lms-test
      - IMAGE_TAG=latest
  build:
    commands:
      - echo installing composer..
      - echo Building the Docker image...
      - docker build -f datamix.production.Dockerfile -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push $REPOSITORY_URI:$IMAGE_TAG
